### ISSUE TITLE
NameError (uninitialized constant Mongoid::Relations::Cascading::DeleteAll):

### ISSUE THREAD

**Issue by S-Cardenas** [doorkeeper-gem/doorkeeper-mongodb#23]
Hello,

I've been receiving the error below when trying to delete one of my applications from http://localhost:3000/api/v1/oauth/applications. 

```
Started DELETE "/api/v1/oauth/applications/5930bd2aa54dd321f7248178" for ::1 at 2017-06-01 21:53:22 -0400
Processing by Doorkeeper::ApplicationsController#destroy as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"+IxdEDUYW65Hj99VUqdJ/rydjZjJE8CIFy7El5KuuZ0rf36wLE0M4qJxBUL61D1IeRW+VvgWw1o9ckXxpHBkVw==", "commit"=>"Destroy", "id"=>"5930bd2aa54dd321f7248178"}
MONGODB | localhost:27017 | playco_development.find | STARTED | {"find"=>"oauth_applications", "filter"=>{"_id"=>BSON::ObjectId('5930bd2aa54dd321f7248178')}}
MONGODB | localhost:27017 | playco_development.find | SUCCEEDED | 0.000784s
Completed 500 Internal Server Error in 9ms

NameError (uninitialized constant Mongoid::Relations::Cascading::DeleteAll):
  activesupport (4.2.8) lib/active_support/inflector/methods.rb:263:in `const_get'
  activesupport (4.2.8) lib/active_support/inflector/methods.rb:263:in `block in constantize'
  activesupport (4.2.8) lib/active_support/inflector/methods.rb:259:in `each'
  activesupport (4.2.8) lib/active_support/inflector/methods.rb:259:in `inject'
  activesupport (4.2.8) lib/active_support/inflector/methods.rb:259:in `constantize'
  activesupport (4.2.8) lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
  mongoid (5.2.1) lib/mongoid/relations/metadata.rb:98:in `cascade_strategy'
  mongoid (5.2.1) lib/mongoid/relations/cascading.rb:30:in `block in cascade!'
```

Here are the gems I am using that are pertinent to mongoid and rails:
```
gem 'rails', '4.2.8'
gem 'mongoid', '~> 5.2.1'gem 'doorkeeper-mongodb', github: 'doorkeeper-gem/doorkeeper-mongodb'
gem "doorkeeper-grants_assertion", github: "doorkeeper-gem/doorkeeper-grants_assertion"
```

This only happens when trying to 'destroy' an existing application from the UI.

Any help would be greatly appreciated.

**Comment by nbulaj** [comment]
@S-Cardenas Mongoid currently doesn't support `delete all` strategy. It [will be added only in 7.0](https://github.com/mongodb/mongoid/blob/7.0-dev/lib/mongoid/association/depending.rb#L18) version of the gem. So for now you need a 1) changes in the gem (don't sure when it would be), 2) implement and require your own `Mongoid::Relations::Cascading::DeleteAll` class and all the logic
