### ISSUE TITLE
Incompatibility with Doorkeeper 3.0.1 (at least with Mongoid 4)

### ISSUE THREAD

**Issue by mdouchement** [doorkeeper-gem/doorkeeper-mongodb#9]
Hello, I have the following bug with Doorkeeper 3.0.1:

```
Started POST "/oauth/token" for 127.0.0.1 at 2015-10-13 11:02:54 +0200
Processing by Doorkeeper::TokensController#create as HTML
Completed 500 Internal Server Error in 3ms

NoMethodError (undefined method `transaction' for #<Doorkeeper::AccessGrant:0x00564532a949d0>):
  doorkeeper (3.0.1) lib/doorkeeper/oauth/authorization_code_request.rb:24:in `before_successful_response'
  doorkeeper (3.0.1) lib/doorkeeper/oauth/request_concern.rb:7:in `authorize'
  doorkeeper (3.0.1) lib/doorkeeper/request/authorization_code.rb:19:in `authorize'
  doorkeeper (3.0.1) app/controllers/doorkeeper/tokens_controller.rb:42:in `authorize_response'
  doorkeeper (3.0.1) app/controllers/doorkeeper/tokens_controller.rb:4:in `create'
  actionpack (4.1.6) lib/abstract_controller/base.rb:189:in `process_action'
  actionpack (4.1.6) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.1.6) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.6) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.1.6) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.1.6) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.1.6) lib/abstract_controller/base.rb:136:in `process'
  actionpack (4.1.6) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.1.6) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.1.6) lib/action_controller/metal.rb:232:in `block in action'
  actionpack (4.1.6) lib/action_dispatch/routing/route_set.rb:82:in `call'
  actionpack (4.1.6) lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
  actionpack (4.1.6) lib/action_dispatch/routing/route_set.rb:50:in `call'
  actionpack (4.1.6) lib/action_dispatch/journey/router.rb:73:in `block in call'
  actionpack (4.1.6) lib/action_dispatch/journey/router.rb:59:in `each'
  actionpack (4.1.6) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.6) lib/action_dispatch/routing/route_set.rb:678:in `call'

  ...
```

This is my Gemfile:

``` rb
# ...

gem 'mongoid', '4.0.2'
gem 'devise', '3.5.2'
gem 'doorkeeper', '3.0.1'
gem 'doorkeeper-mongodb', github: 'doorkeeper-gem/doorkeeper-mongodb'

# ...
```

<br>
<br>
After a short investigation, I have found that the following [method](https://github.com/doorkeeper-gem/doorkeeper/blob/v3.0.1/lib%2Fdoorkeeper%2Foauth%2Fauthorization_code_request.rb#L23-L34) in Doorkeeper 3.0.1 use specific ActiveRecord's stuff:

``` rb
def before_successful_response
  grant.transaction do
    grant.lock!
    raise Errors::InvalidGrantReuse if grant.revoked?

    grant.revoke
    find_or_create_access_token(grant.application,
                                grant.resource_owner_id,
                                grant.scopes,
                                server)
  end
end
```

So this code breaks compatibility with Mongoid 4 and this gem.

**Comment by jasl** [comment]
I'm trying resolve this.

MongoDB doesn't have `transaction`

**Comment by icostan** [comment]
Any update on this?

**Comment by okdas** [comment]
What a sad bug.

We can try to ignore transaction, but is it safe?

**Comment by lihuazhang** [comment]
@jasl any update？

**Comment by jasl** [comment]
@lihuazhang 
@icostan 
plz checkout the latest master commit, It's should support Mongoid 5 and compatible with latest Doorkeeper

but 1 test still not pass, I think that's not critical.

```
  1) Doorkeeper::OAuth::TokenRequest token reuse skips token creation if there is a matching one
     Failure/Error: subject.authorize
       Double received unexpected message :has_scopes? with (#<Doorkeeper::OAuth::Scopes:0x007fe117dc0988 @scopes=["public"]>)
     # /Users/Jasl/.rvm/gems/ruby-2.2.3/gems/doorkeeper-3.0.1/lib/doorkeeper/oauth/helpers/scope_checker.rb:17:in `valid?'
     # /Users/Jasl/.rvm/gems/ruby-2.2.3/gems/doorkeeper-3.0.1/lib/doorkeeper/oauth/helpers/scope_checker.rb:21:in `match?'
     # /Users/Jasl/.rvm/gems/ruby-2.2.3/gems/doorkeeper-3.0.1/lib/doorkeeper/oauth/helpers/scope_checker.rb:40:in `match?'
     # /Users/Jasl/.rvm/gems/ruby-2.2.3/gems/doorkeeper-3.0.1/lib/doorkeeper/models/access_token_mixin.rb:63:in `scopes_match?'
     # /Users/Jasl/.rvm/gems/ruby-2.2.3/gems/doorkeeper-3.0.1/lib/doorkeeper/models/access_token_mixin.rb:56:in `matching_token_for'
     # /Users/Jasl/.rvm/gems/ruby-2.2.3/gems/doorkeeper-3.0.1/lib/doorkeeper/models/access_token_mixin.rb:72:in `find_or_create_for'
     # /Users/Jasl/.rvm/gems/ruby-2.2.3/gems/doorkeeper-3.0.1/lib/doorkeeper/oauth/authorization/token.rb:21:in `issue_token'
     # /Users/Jasl/.rvm/gems/ruby-2.2.3/gems/doorkeeper-3.0.1/lib/doorkeeper/oauth/token_request.rb:15:in `authorize'
     # ./spec/lib/oauth/token_request_spec.rb:90:in `block (4 levels) in <module:OAuth>'
     # ./spec/lib/oauth/token_request_spec.rb:89:in `block (3 levels) in <module:OAuth>'
```

**Comment by jasl** [comment]
Recent updates I refactor about testing(old have some issues that not following the upstream changes actually)

```
Failures:

  1) Doorkeeper::OAuth::ClientCredentialsRequest::Creator returns false if creation fails
     Failure/Error: expect(created).to be_falsey

       expected: falsey value
            got: #<Doorkeeper::AccessToken _id: 565c189675c27f9613000010, created_at: 2015-11-30 09:36:22 UTC, updated_at: 2015-11-30 09:36:22 UTC, application_id: BSON::ObjectId('565c189675c27f961300000f'), scopes: "public", resource_owner_id: nil, token: "71360e4229de929cf60507f7440e93484e80c02408efebe869d89421dfe2751a", refresh_token: nil, expires_in: nil, revoked_at: nil>
     # ./spec/lib/oauth/client_credentials/creator_spec.rb:17:in `block (2 levels) in <class:ClientCredentialsRequest>'

  2) Refresh Token Flow issuing a refresh token client gets the refresh token and refreshses it
     Failure/Error: expect(JSON.parse(response.body).fetch(key)).to eq(value)

       expected: "08a51908df3b8799021f41aab2d1cd962cc7ed9771d190748bcdd8eadc0d9ece"
            got: "f5a6c91c55c68972707e730c1bbe300245700d2eb1ecfca8975cddba07499657"

       (compared using ==)
     # ./spec/support/helpers/request_spec_helper.rb:47:in `should_have_json'
     # ./spec/requests/flows/refresh_token_spec.rb:30:in `block (3 levels) in <top (required)>'

  3) Refresh Token Flow refreshing the token client request a token with expired access token
     Failure/Error: expect(JSON.parse(response.body).fetch(key)).to eq(value)

       expected: "471d20bcf0c96f7a51651b843728298f846ab0759a9d980407a57412ecdaed08"
            got: "47f130b0e309636830f64b20cebf18959a704339f1fbab5c624e00167430e23b"

       (compared using ==)
     # ./spec/support/helpers/request_spec_helper.rb:47:in `should_have_json'
     # ./spec/requests/flows/refresh_token_spec.rb:52:in `block (3 levels) in <top (required)>'

  4) Refresh Token Flow refreshing the token client request a token with refresh token
     Failure/Error: expect(JSON.parse(response.body).fetch(key)).to eq(value)

       expected: "cd48505ce7a91df12ebecdd52af1d5b25314e372aab21a28dfef555e141b3c45"
            got: "d25f89a298a135fb51d6ff561b265403f1d5553cb3f246da3bc8cf7adc8fa558"

       (compared using ==)
     # ./spec/support/helpers/request_spec_helper.rb:47:in `should_have_json'
     # ./spec/requests/flows/refresh_token_spec.rb:45:in `block (3 levels) in <top (required)>'

  5) Doorkeeper::Server.authorization_request builds the request with selected strategy
     Failure/Error: subject.authorization_request :code
       #<Double :fake_class> received unexpected message :new with (#<Doorkeeper::Server:0x007f8c30394270 @context=nil>)
     # /Users/jasl/.rvm/gems/ruby-2.2.3/bundler/gems/doorkeeper-5492713189f9/lib/doorkeeper/server.rb:11:in `authorization_request'
     # ./spec/lib/server_spec.rb:49:in `block (3 levels) in <top (required)>'

  6) Doorkeeper::OAuth::TokenRequest token reuse skips token creation if there is a matching one
     Failure/Error: subject.authorize
       #<Double (anonymous)> received unexpected message :has_scopes? with (#<Doorkeeper::OAuth::Scopes:0x007f8c30557990 @scopes=["public"]>)
     # /Users/jasl/.rvm/gems/ruby-2.2.3/bundler/gems/doorkeeper-5492713189f9/lib/doorkeeper/oauth/helpers/scope_checker.rb:17:in `valid?'
     # /Users/jasl/.rvm/gems/ruby-2.2.3/bundler/gems/doorkeeper-5492713189f9/lib/doorkeeper/oauth/helpers/scope_checker.rb:21:in `match?'
     # /Users/jasl/.rvm/gems/ruby-2.2.3/bundler/gems/doorkeeper-5492713189f9/lib/doorkeeper/oauth/helpers/scope_checker.rb:40:in `match?'
     # /Users/jasl/.rvm/gems/ruby-2.2.3/bundler/gems/doorkeeper-5492713189f9/lib/doorkeeper/models/access_token_mixin.rb:63:in `scopes_match?'
     # /Users/jasl/.rvm/gems/ruby-2.2.3/bundler/gems/doorkeeper-5492713189f9/lib/doorkeeper/models/access_token_mixin.rb:56:in `matching_token_for'
     # /Users/jasl/.rvm/gems/ruby-2.2.3/bundler/gems/doorkeeper-5492713189f9/lib/doorkeeper/models/access_token_mixin.rb:72:in `find_or_create_for'
     # /Users/jasl/.rvm/gems/ruby-2.2.3/bundler/gems/doorkeeper-5492713189f9/lib/doorkeeper/oauth/authorization/token.rb:21:in `issue_token'
     # /Users/jasl/.rvm/gems/ruby-2.2.3/bundler/gems/doorkeeper-5492713189f9/lib/doorkeeper/oauth/token_request.rb:15:in `authorize'
     # ./spec/lib/oauth/token_request_spec.rb:90:in `block (4 levels) in <module:OAuth>'
     # ./spec/lib/oauth/token_request_spec.rb:89:in `block (3 levels) in <module:OAuth>'

  7) Doorkeeper::OAuth::RefreshTokenRequest issues a new token for the client
     Failure/Error: expect(client.reload.access_tokens.last.expires_in).to eq(120)

       expected: 120
            got: 7200

       (compared using ==)
     # ./spec/lib/oauth/refresh_token_request_spec.rb:22:in `block (2 levels) in <module:OAuth>'

  8) Doorkeeper::OAuth::RefreshTokenRequest issues a new token for the client with custom expires_in
     Failure/Error: expect(client.reload.access_tokens.last.expires_in).to eq(1234)

       expected: 1234
            got: 7200

       (compared using ==)
     # ./spec/lib/oauth/refresh_token_request_spec.rb:32:in `block (2 levels) in <module:OAuth>'

  9) Doorkeeper::OAuth::RefreshTokenRequest with scopes uses params[:scope] in favor of scopes if present (valid)
     Failure/Error: expect(Doorkeeper::AccessToken.last.scopes).to eq([:public])

       expected: [:public]
            got: #<Doorkeeper::OAuth::Scopes:0x007f8c319b9a50 @scopes=["public", "write"]>

       (compared using ==)

       Diff:
       @@ -1,2 +1,2 @@
       -[:public]
       +["public", "write"]

     # ./spec/lib/oauth/refresh_token_request_spec.rb:111:in `block (3 levels) in <module:OAuth>'

  10) Doorkeeper::OAuth::RefreshTokenRequest with scopes reduces scopes to the provided scopes
      Failure/Error: expect(Doorkeeper::AccessToken.last.scopes).to eq([:public])

        expected: [:public]
             got: #<Doorkeeper::OAuth::Scopes:0x007f8c29daa9f0 @scopes=["public", "write"]>

        (compared using ==)

        Diff:
        @@ -1,2 +1,2 @@
        -[:public]
        +["public", "write"]

      # ./spec/lib/oauth/refresh_token_request_spec.rb:97:in `block (3 levels) in <module:OAuth>'

  11) Doorkeeper::OAuth::Error description is translated from translation messages
      Failure/Error: subject.description

        I18n received :translate with unexpected arguments
          expected: (:some_error, {:scope=>[:doorkeeper, :errors, :messages]})
               got: (:some_error, {:scope=>[:doorkeeper, :errors, :messages], :default=>:server_error})
        Diff:
        @@ -1,2 +1,3 @@
        -[:some_error, {:scope=>[:doorkeeper, :errors, :messages]}]
        +[:some_error,
        + {:scope=>[:doorkeeper, :errors, :messages], :default=>:server_error}]

      # /Users/jasl/.rvm/gems/ruby-2.2.3/bundler/gems/doorkeeper-5492713189f9/lib/doorkeeper/oauth/error.rb:5:in `description'
      # ./spec/lib/oauth/error_spec.rb:15:in `block (3 levels) in <module:OAuth>'

Finished in 7.74 seconds (files took 1.63 seconds to load)
529 examples, 11 failures, 7 pending
```

For now I've resolving issues that would raising errors

but there still a lot of works to do, both on doorkeeper-mongodb and doorkeeper sides.

**Comment by jasl** [comment]
I was refactor doorkeeper models that give a possibility to extracting ORM supporting, but THAT is still initial step in my opinion.

In this year I'm leading a team for a startup company so I didn't have much time to working for community, so I couldn't maintain the gem, but I will try to working on these issues.

**Comment by nbulaj** [comment]
Hi @mdouchement. Do you still have a reported issue? Even 3.0 version of this gem has `transaction` hack for MongoDB. Also if you are using Doorkeeper >= 4, then you can update `doorkeeper-mongodb` to a new version.

**Comment by mdouchement** [comment]
Hello. thanks for the update. I no longer use `doorkeeper-mongodb` gem because my project has been stopped. So I can't tell you if this bug is still running.

If you are confident that this bug is now resolved, you can close this issue.
